### ISSUE TITLE
FEMA crates have nothing in them

### ISSUE THREAD

**Issue by Thecringeguy721** [TEHE-Studios/ExpandedHelicopterEvents#104]
I don't know if this happened to anyone else but whenever a FEMA supply drop comes there's always nothing in them, i don't know if one of my mods are interfering with it but it's gotten to a point to whenever a helicopter comes over I just ignore the drop because i expect there to be nothing in it.

**Comment by ChuckTheSheep** [comment]
Are you using any mods that lower loot chance?

**Comment by Thecringeguy721** [comment]
No i've doubled checked too i've also disabled all my mods but loot still won't appear in it

**Comment by Nerdgamerdave** [comment]
Also having this on my MP server.

We had 3 FEMA drops before the latest update. no issue and got a handful of supply boxes in each as expected.

Since the update, 8/8 FEMA drops and one I spawned in as admin are all 100% empty.  No other changes made to the server, spawn rates or other settings.

Highly suggestive it's due to the latest update with the color coding and attack chopper add-on

**Comment by ChuckTheSheep** [comment]
A user by name of I2A on the Pz discord sat down with his mods and figured out the Sheriff Expanded Heli mod (not affiliated with us) broke his loot boxes.

If you use that mod in a MP setting try to load it first or not at all.
