### ISSUE TITLE
Please make older mod versions available 

### ISSUE THREAD

**Issue by Kara-bit** [TEHE-Studios/ExpandedHelicopterEvents#181]
Some people like playing on older versions of the game and don't want to have to update an entire library of mods to update the game to be able to get this one mod, please make the older releases of the mod (41.65 etc) available.

**Comment by ChuckTheSheep** [comment]
For context, the version minimum was set to 41.66 on Feb 5, 2023. 6978c5e172c328b4b169ab2e4bc6028860f39987

This was done for a number of reasons:
 - The biggest being this was mostly a 2 man team (now 3) with some occasional help for voice, sound, and translation.
 - Supporting old versions is impractical due to ongoing changes in the base game along with bug reports from users on older versions.

**So the current plan is to continuously update that version minimum as it is updated to work on the base game.**

Furthermore, steam does not have a method of hosting multiple versions under the same mod-page, and packing older versions as sub-mods would bloat the project's size. Additionally, and personally, I don't want to publish multiple mods for this purpose.


That being said, what do you mean by update an entire library of mods?
