### ISSUE TITLE
AEBS announcing bugged

### ISSUE THREAD

**Issue by smallerYeet** [TEHE-Studios/ExpandedHelicopterEvents#81]
On my dedicated server, I have the problem that the mod is constantly telling me AEBS_SupplyDrop.
There is no helicopter around and no events are getting triggered.
![grafik](https://user-images.githubusercontent.com/68237474/193041259-84f710b5-845f-4b4e-abbe-31c416bae8cc.png)

**Comment by Steelherd** [comment]
im having the same issue with the bugged radio announcements on my dedicated server, however I do get the helicopter event as a helicopter flew near my base, the marker popped up correctly as it flew past.

**Comment by ChuckTheSheep** [comment]
Will be looking into translation issues.

**Comment by Olipro** [comment]
This is an issue that affected Save Our Station too. It would seem that at some point PZ was changed to not load localisation strings on the server. This results in `getRadioText()` being a no-op.

Unfortunately, since there is no interception point for radio strings on the client, the best you can do is move all your strings into code instead.
